name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies in back-end
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Install dependencies in front-end
        run: npm install
        working-directory: bloglist-frontend
      - name: jest tests back-end
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
      - name: jest tests front-end
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
        working-directory: bloglist-frontend

      - name: build
        run: npm run build
        working-directory: bloglist-frontend
      - name: copy dist
        run: cp -r ./bloglist-frontend/dist .
        
      - name: e2e tests
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        uses: cypress-io/github-action@v5
        with:
          command: npm --prefix ./bloglist-frontend run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3000

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
        if: ${{ (github.event_name == 'push') && (!contains(join(github.event.head_commit.message, ', '), '#skip')) }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Discord Webhook Notify
        uses: stegzilla/discord-notify@v4
        if: failure()
        with:
          colour: "#ff3333"
          title: Build failed
          message: "commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username}} failed :("
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    if: ${{ (github.event_name == 'push') && (!contains(join(github.event.head_commit.message,', '), '#skip')) }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Discord Webhook Notify
        uses: stegzilla/discord-notify@v4
        if: success()
        with:
          title: A new version of Pokedex deployed
          message: "to https://full-stack-open-pokedex-weathered-pond-1509.fly.dev/"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
