name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies in back-end
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Install dependencies in front-end
        run: npm install
        working-directory: bloglist-frontend
      - name: jest tests back-end
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
      - name: jest tests front-end
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
        working-directory: bloglist-frontend
      - name: e2e tests
        env:
          TEST_MONTODB_URI: ${{ secrets.TEST_MONTODB_URI }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3000
        
